#+TITLE: phutball

This repository contains (well, it will contain) several algorithms
that play [[https://en.wikipedia.org/wiki/Phutball][Phutball]].

I oriented the board horizontally, following Berlekamp, Conway, and
Guy's convention in /Winning Ways for Your Mathematical Plays/ (pp.
752--755). Wikipedia orients it vertically.

Left (which always goes first) tries to get the ball (black circle)
all the way to the right (i.e. in Right's goal), and vice versa.




Place a man by entering the desired position, e.g. Left might begin
with ~H11~:

#+BEGIN_EXAMPLE
          1111111111
 1234567890123456789
A+++++++++++++++++++
B+++++++++++++++++++
C+++++++++++++++++++
D+++++++++++++++++++
E+++++++++++++++++++
F+++++++++++++++++++
G+++++++++++++++++++
H+++++++++●○++++++++
I+++++++++++++++++++
J+++++++++++++++++++
K+++++++++++++++++++
L+++++++++++++++++++
M+++++++++++++++++++
N+++++++++++++++++++
O+++++++++++++++++++
#+END_EXAMPLE

Make a jump by indicating the compass directions. For example, suppose
the board looks like this:



#+BEGIN_EXAMPLE
          1111111111
 1234567890123456789
A+++++++++++++++++++
B+++++++++++++++++++
C+++++++++++++++++++
D+++++++++++++++++++
E+++++++++++++++++++
F+++++++++++++++++++
G++++++++++++++○++++
H++++++○○○●○+○++++++
I+++++++++++++++++++
J+++++++++++++++++++
K+++++++++++++++++++
L+++++++++++++++++++
M+++++++++++++++++++
N+++++++++++++++++++
O+++++++++++++++++++
#+END_EXAMPLE

Left types ~E E NE~ and obtains:

#+BEGIN_EXAMPLE
          1111111111
 1234567890123456789
A+++++++++++++++++++
B+++++++++++++++++++
C+++++++++++++++++++
D+++++++++++++++++++
E+++++++++++++++++++
F+++++++++++++++●+++
G+++++++++++++++++++
H++++++○○○++++++++++
I+++++++++++++++++++
J+++++++++++++++++++
K+++++++++++++++++++
L+++++++++++++++++++
M+++++++++++++++++++
N+++++++++++++++++++
O+++++++++++++++++++
#+END_EXAMPLE


If it were Right's turn, they could type ~W~ and jump all three men
(white circles) at once, since making a shorter jump to the west isn't
possible.


Currently the only AI is PloddingPlayer, which either places a man
directly next to the ball, or makes a jump if that's possible. You can
play against it by running:


#+BEGIN_SRC python
import main
main.run_game( (main.PloddingPlayer(), main.HumanPlayer() ) )
#+END_SRC


* Files

~data.zip~ currently contains these files, added using ~zip data.zip *pickle~:

#+BEGIN_EXAMPLE
$ du -hs *pickle
 22M	2021-04-02-3ply-boards1.pickle
3.0M	2021-04-02-3ply-games1.pickle
 80M	2021-04-07-3ply-boards2.pickle
103M	2021-04-07-3ply-data1.pickle
8.0K	2021-05-06-3ply-boards3.pickle
#+END_EXAMPLE
