#+TITLE: phutball

This repository contains several algorithms
that play [[https://en.wikipedia.org/wiki/Phutball][Phutball]] (and it will contain more eventually).

I oriented the board horizontally, following Berlekamp, Conway, and
Guy's convention in /Winning Ways for Your Mathematical Plays/ (pp.
752--755). Wikipedia orients it vertically.

Left (which always goes first) tries to get the ball (black circle)
all the way to the right (i.e. in Right's goal), and vice versa.




Place a man by entering the desired position, e.g. Left might begin
with ~H11~:

#+BEGIN_EXAMPLE
          1111111111
 1234567890123456789
A+++++++++++++++++++
B+++++++++++++++++++
C+++++++++++++++++++
D+++++++++++++++++++
E+++++++++++++++++++
F+++++++++++++++++++
G+++++++++++++++++++
H+++++++++●○++++++++
I+++++++++++++++++++
J+++++++++++++++++++
K+++++++++++++++++++
L+++++++++++++++++++
M+++++++++++++++++++
N+++++++++++++++++++
O+++++++++++++++++++
#+END_EXAMPLE

Make a jump by indicating the compass directions. For example, suppose
the board looks like this:



#+BEGIN_EXAMPLE
          1111111111
 1234567890123456789
A+++++++++++++++++++
B+++++++++++++++++++
C+++++++++++++++++++
D+++++++++++++++++++
E+++++++++++++++++++
F+++++++++++++++++++
G++++++++++++++○++++
H++++++○○○●○+○++++++
I+++++++++++++++++++
J+++++++++++++++++++
K+++++++++++++++++++
L+++++++++++++++++++
M+++++++++++++++++++
N+++++++++++++++++++
O+++++++++++++++++++
#+END_EXAMPLE

Left types ~E E NE~ and obtains:

#+BEGIN_EXAMPLE
          1111111111
 1234567890123456789
A+++++++++++++++++++
B+++++++++++++++++++
C+++++++++++++++++++
D+++++++++++++++++++
E+++++++++++++++++++
F+++++++++++++++●+++
G+++++++++++++++++++
H++++++○○○++++++++++
I+++++++++++++++++++
J+++++++++++++++++++
K+++++++++++++++++++
L+++++++++++++++++++
M+++++++++++++++++++
N+++++++++++++++++++
O+++++++++++++++++++
#+END_EXAMPLE


If it were Right's turn, they could type ~W~ and jump all three men
(white circles) at once, since making a shorter jump to the west isn't
possible.


The simplest AI is PloddingPlayer, which either places a man
directly next to the ball, or makes a jump if that's possible. You can
play against it by running:


#+BEGIN_SRC python
import main
main.run_game( (main.PloddingPlayer(), main.HumanPlayer() ) )
#+END_SRC

A more advanced AI is NegamaxABPlayer. Unfortunately it's currently weaker than PloddingPlayer.
(See [[https://lettertok.com/index.php/2021/03/24/rules-of-phutball/][these]] [[http://lettertok.com/index.php/2021/03/31/a-fancier-algorithm/][three]] [[http://lettertok.com/index.php/2021/04/07/groundhog-day/][posts]] for more discussion of this. Likely I need to make better training data.)

* Files

~data.zip~ currently contains these files, added using ~zip data.zip *pickle~:

#+BEGIN_EXAMPLE
$ du -hs *pickle
 22M    2021-04-02-3ply-boards1.pickle
2.6M    2021-04-02-3ply-games1.pickle
 73M    2021-04-07-3ply-boards2.pickle
103M    2021-04-07-3ply-data1.pickle
 30M    2021-05-06-3ply-boards3.pickle
 26M    2021-07-24-3ply-boards4.pickle
 28M    2021-08-04-3ply-boards5.pickle
 22M    2021-08-11-3ply-v2-boards6-random.pickle
 26M    2021-08-16-3ply-v2-boards7-games.pickle
 19M    2021-08-23-3ply-v3-boards8-random.pickle
 22M    2021-08-28-3ply-v3-boards9-games.pickle
#+END_EXAMPLE
